# Generated by Django 5.2.12 on 2026-03-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
        ("reports", "0003_branch_businesssettings_cloud_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="reports.branch",
            ),
        ),
    ]
