# Generated by Django 5.2.12 on 2026-03-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_purchase_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="invoice_no",
            field=models.CharField(max_length=100),
        ),
    ]
