# Generated by Django 5.2.12 on 2026-03-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("sales", "Sales"),
                            ("inventory", "Inventory"),
                            ("products", "Products"),
                            ("purchases", "Purchases"),
                            ("users", "Users"),
                            ("settings", "Settings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("entity_type", models.CharField(blank=True, max_length=100)),
                ("entity_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
