# Generated by Django 5.2.12 on 2026-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_email_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[("password_reset", "Password Reset")], max_length=20
            ),
        ),
    ]
