# Generated by Django 5.2.12 on 2026-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="after_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="before_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
