# Generated by Django 5.2.12 on 2026-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventorylog_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("refund", "Refund"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
