# Generated by Django 5.2.12 on 2026-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="DurielBiz POS", max_length=255),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "receipt_footer",
                    models.CharField(
                        blank=True,
                        default="Thank you for your patronage.",
                        max_length=255,
                    ),
                ),
                ("loyalty_points_per_1000", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "business settings",
            },
        ),
    ]
