# Generated by Django 5.2.12 on 2026-03-10 12:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="loyalty_cash_value_per_point",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=8
            ),
        ),
    ]
