# Generated by Django 5.2.12 on 2026-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_branch_businesssettings_cloud_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="auto_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="auto_sync_interval_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="last_cloud_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
