# Generated by Django 5.2.12 on 2026-07-08 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_businesssettings_auto_sync_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="vat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="vat_rate_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
    ]
