# Generated by Django 5.2.4 on 2026-03-19 11:45

from django.db import migrations, models


def backfill_paid_access(apps, schema_editor):
    ToolSubscription = apps.get_model("invoicing", "ToolSubscription")
    ToolSubscription.objects.filter(status="active").update(
        has_paid_access=True,
        plan_name="30-Day Paid Subscription",
    )


def reverse_backfill_paid_access(apps, schema_editor):
    ToolSubscription = apps.get_model("invoicing", "ToolSubscription")
    ToolSubscription.objects.filter(status="active", has_paid_access=True).update(
        has_paid_access=False,
        plan_name="Monthly Subscription",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_document_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsubscription',
            name='has_paid_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toolsubscription',
            name='plan_name',
            field=models.CharField(default='48-Hour Free Trial', max_length=80),
        ),
        migrations.AlterField(
            model_name='toolsubscription',
            name='status',
            field=models.CharField(choices=[('trial', '48-Hour Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.RunPython(backfill_paid_access, reverse_backfill_paid_access),
    ]
