# Generated by Django 5.2.4 on 2026-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_toolsubscription_has_paid_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature_initials',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_mode',
            field=models.CharField(choices=[('blank', 'Leave Blank'), ('initials', 'Use Initials')], default='blank', max_length=20),
        ),
    ]
