# Generated by Django 5.2.12 on 2026-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_loyalty_points_awarded_sale_redeemed_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_redeem_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
